//exports from: ./bin/Debug/net7.0
#r @"bin/Debug/net7.0/Microsoft.VisualStudio.TestPlatform.ObjectModel.dll"
#r @"bin/Debug/net7.0/Sbre.Test.dll"
#r @"bin/Debug/net7.0/xunit.abstractions.dll"
#r @"bin/Debug/net7.0/xunit.runner.visualstudio.dotnetcore.testadapter.dll"
#r @"bin/Debug/net7.0/Microsoft.TestPlatform.CrossPlatEngine.dll"
#r @"bin/Debug/net7.0/Microsoft.TestPlatform.CommunicationUtilities.dll"
#r @"bin/Debug/net7.0/xunit.runner.reporters.netcoreapp10.dll"
#r @"bin/Debug/net7.0/NuGet.Frameworks.dll"
#r @"bin/Debug/net7.0/Microsoft.TestPlatform.Utilities.dll"
#r @"bin/Debug/net7.0/Microsoft.TestPlatform.CoreUtilities.dll"
#r @"bin/Debug/net7.0/xunit.execution.dotnet.dll"
#r @"bin/Debug/net7.0/xunit.assert.dll"
#r @"bin/Debug/net7.0/Microsoft.TestPlatform.PlatformAbstractions.dll"
#r @"bin/Debug/net7.0/Microsoft.VisualStudio.CodeCoverage.Shim.dll"
#r @"bin/Debug/net7.0/Microsoft.VisualStudio.TestPlatform.Common.dll"
#r @"bin/Debug/net7.0/FSharp.Core.dll"
#r @"bin/Debug/net7.0/xunit.runner.utility.netcoreapp10.dll"
#r @"bin/Debug/net7.0/testhost.dll"
#r @"bin/Debug/net7.0/RuntimeRegexCopy.dll"
#r @"bin/Debug/net7.0/Newtonsoft.Json.dll"
#r @"bin/Debug/net7.0/Sbre.dll"
#r @"bin/Debug/net7.0/xunit.core.dll"
#r @"bin/Debug/net7.0/FSharpPlus.dll"
//
//no lib found
