//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("System.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Generic {
            get {
                return "Generic";
            }
        }
        
        internal static string AlternationHasNamedCapture {
            get {
                return "AlternationHasNamedCapture";
            }
        }
        
        internal static string AlternationHasComment {
            get {
                return "AlternationHasComment";
            }
        }
        
        internal static string Arg_ArrayPlusOffTooSmall {
            get {
                return "Arg_ArrayPlusOffTooSmall";
            }
        }
        
        internal static string ShorthandClassInCharacterRange {
            get {
                return "ShorthandClassInCharacterRange";
            }
        }
        
        internal static string BeginIndexNotNegative {
            get {
                return "BeginIndexNotNegative";
            }
        }
        
        internal static string QuantifierOrCaptureGroupOutOfRange {
            get {
                return "QuantifierOrCaptureGroupOutOfRange";
            }
        }
        
        internal static string CaptureGroupOfZero {
            get {
                return "CaptureGroupOfZero";
            }
        }
        
        internal static string CountTooSmall {
            get {
                return "CountTooSmall";
            }
        }
        
        internal static string EnumNotStarted {
            get {
                return "EnumNotStarted";
            }
        }
        
        internal static string AlternationHasMalformedCondition {
            get {
                return "AlternationHasMalformedCondition";
            }
        }
        
        internal static string IllegalDefaultRegexMatchTimeoutInAppDomain {
            get {
                return "IllegalDefaultRegexMatchTimeoutInAppDomain";
            }
        }
        
        internal static string UnescapedEndingBackslash {
            get {
                return "UnescapedEndingBackslash";
            }
        }
        
        internal static string ReversedQuantifierRange {
            get {
                return "ReversedQuantifierRange";
            }
        }
        
        internal static string InvalidUnicodePropertyEscape {
            get {
                return "InvalidUnicodePropertyEscape";
            }
        }
        
        internal static string CaptureGroupNameInvalid {
            get {
                return "CaptureGroupNameInvalid";
            }
        }
        
        internal static string LengthNotNegative {
            get {
                return ResourceManager.GetString("LengthNotNegative", resourceCulture);
            }
        }
        
        internal static string MalformedNamedReference {
            get {
                return ResourceManager.GetString("MalformedNamedReference", resourceCulture);
            }
        }
        
        internal static string AlternationHasMalformedReference {
            get {
                return ResourceManager.GetString("AlternationHasMalformedReference", resourceCulture);
            }
        }
        
        internal static string MalformedUnicodePropertyEscape {
            get {
                return ResourceManager.GetString("MalformedUnicodePropertyEscape", resourceCulture);
            }
        }
        
        internal static string MakeException {
            get
            {
                return nameof(MakeException);
            }
        }
        
        internal static string MissingControlCharacter {
            get {
                return ResourceManager.GetString("MissingControlCharacter", resourceCulture);
            }
        }
        
        internal static string NestedQuantifiersNotParenthesized {
            get {
                return ResourceManager.GetString("NestedQuantifiersNotParenthesized", resourceCulture);
            }
        }
        
        internal static string NoResultOnFailed {
            get {
                return ResourceManager.GetString("NoResultOnFailed", resourceCulture);
            }
        }
        
        internal static string InsufficientClosingParentheses {
            get {
                return ResourceManager.GetString("InsufficientClosingParentheses", resourceCulture);
            }
        }
        
        internal static string NotSupported_ReadOnlyCollection {
            get {
                return ResourceManager.GetString("NotSupported_ReadOnlyCollection", resourceCulture);
            }
        }
        
        internal static string PlatformNotSupported_CompileToAssembly {
            get {
                return ResourceManager.GetString("PlatformNotSupported_CompileToAssembly", resourceCulture);
            }
        }
        
        internal static string QuantifierAfterNothing {
            get {
                return ResourceManager.GetString("QuantifierAfterNothing", resourceCulture);
            }
        }
        
        internal static string RegexMatchTimeoutException_Occurred {
            get {
                return ResourceManager.GetString("RegexMatchTimeoutException_Occurred", resourceCulture);
            }
        }
        
        internal static string ReversedCharacterRange {
            get {
                return ResourceManager.GetString("ReversedCharacterRange", resourceCulture);
            }
        }
        
        internal static string ExclusionGroupNotLast {
            get
            {
                return "ExclusionGroupNotLast";
            }
        }
        
        internal static string InsufficientOrInvalidHexDigits {
            get
            {
                return "InsufficientOrInvalidHexDigits";
            }
        }
        
        internal static string AlternationHasTooManyConditions {
            get
            {
                return "AlternationHasTooManyConditions";
            }
        }
        
        internal static string InsufficientOpeningParentheses {
            get
            {
                return "InsufficientOpeningParentheses";
            }
        }
        
        internal static string UndefinedNumberedReference {
            get {
                return nameof(UndefinedNumberedReference);
            }
        }
        
        internal static string UndefinedNamedReference {
            get {
                return ResourceManager.GetString("UndefinedNamedReference", resourceCulture);
            }
        }
        
        internal static string AlternationHasUndefinedReference {
            get {
                return ResourceManager.GetString("AlternationHasUndefinedReference", resourceCulture);
            }
        }
        
        internal static string UnrecognizedUnicodeProperty {
            get {
                return ResourceManager.GetString("UnrecognizedUnicodeProperty", resourceCulture);
            }
        }
        
        internal static string UnrecognizedControlCharacter {
            get {
                return ResourceManager.GetString("UnrecognizedControlCharacter", resourceCulture);
            }
        }
        
        internal static string UnrecognizedEscape {
            get {
                return ResourceManager.GetString("UnrecognizedEscape", resourceCulture);
            }
        }
        
        
        internal static string NotSupported_NonBacktrackingAndReplacementsWithSubstitutionsOfGroups {
            get {
                return ResourceManager.GetString("NotSupported_NonBacktrackingAndReplacementsWithSubstitutionsOfGroups", resourceCulture);
            }
        }
        
        internal static string NotSupported_NonBacktrackingConflictingExpression {
            get {
                return ResourceManager.GetString("NotSupported_NonBacktrackingConflictingExpression", resourceCulture);
            }
        }
        
        internal static string NotSupported_NonBacktrackingUnsafeSize {
            get {
                return ResourceManager.GetString("NotSupported_NonBacktrackingUnsafeSize", resourceCulture);
            }
        }
        
        internal static string ExpressionDescription_Backreference {
            get {
                return ResourceManager.GetString("ExpressionDescription_Backreference", resourceCulture);
            }
        }
        
        internal static string ExpressionDescription_Conditional {
            get {
                return ResourceManager.GetString("ExpressionDescription_Conditional", resourceCulture);
            }
        }
        
        internal static string ExpressionDescription_PositiveLookaround {
            get {
                return ResourceManager.GetString("ExpressionDescription_PositiveLookaround", resourceCulture);
            }
        }
        
        internal static string ExpressionDescription_NegativeLookaround {
            get {
                return ResourceManager.GetString("ExpressionDescription_NegativeLookaround", resourceCulture);
            }
        }
        
        internal static string ExpressionDescription_ContiguousMatches {
            get {
                return ResourceManager.GetString("ExpressionDescription_ContiguousMatches", resourceCulture);
            }
        }
        
        internal static string ExpressionDescription_AtomicSubexpressions {
            get {
                return ResourceManager.GetString("ExpressionDescription_AtomicSubexpressions", resourceCulture);
            }
        }
        
        internal static string ExpressionDescription_IfThenElse {
            get {
                return ResourceManager.GetString("ExpressionDescription_IfThenElse", resourceCulture);
            }
        }
        
        internal static string ExpressionDescription_BalancingGroup {
            get {
                return ResourceManager.GetString("ExpressionDescription_BalancingGroup", resourceCulture);
            }
        }
        
        internal static string UsingSpanAPIsWithCompiledToAssembly {
            get {
                return ResourceManager.GetString("UsingSpanAPIsWithCompiledToAssembly", resourceCulture);
            }
        }
    }
}
